name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v1.2.3

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    
    - name: Compress Executable
      run: |
        $exe = Get-ChildItem -Path .\target\release\ -Filter *.exe
        Compress-Archive -Path $exe -DestinationPath .\target\debug\OnPurpose.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Initial Release
        draft: true
        prerelease: false